name: gymtrak
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphic: ^2.2.1
  vector_math: ^2.1.0
  path_drawing: ^1.0.0
  collection: ^1.15.0
  intl: ^0.19.0
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_svg: ^2.0.9
  material_symbols_icons: ^4.2713.0
  path_provider: ^2.1.1
  sembast: ^3.5.0+1
  numberpicker: ^2.1.2
  permission_handler: ^11.1.0
  awesome_notifications_core: ^0.9.0
  awesome_notifications: any
  shared_preferences: 2.0.15
  syncfusion_flutter_calendar: ^24.2.5+1
  syncfusion_flutter_charts: ^24.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
