import 'package:gymtrak/utilities/bloodwork/dataclasses/bloodwork_category.dart';
import 'package:gymtrak/utilities/bloodwork/dataclasses/bloodwork_parameter.dart';
import 'package:gymtrak/utilities/medication/dataclasses/medication_component.dart';
import 'package:gymtrak/utilities/medication/dataclasses/medication_category.dart';

List<BloodWorkParameter> parametersInitial = [
  // A
  BloodWorkParameter(
    name: 'ACE',
    fullName: 'Angiotensin Converting Enzyme',
    category: ParameterCategoryClass.getName(ParameterCategory.heart),
    upperLimit: 100,
    lowerLimit: 0,
    unit: 'U/L',
  ),
  BloodWorkParameter(
    name: 'ALAT',
    fullName: 'Alanine Aminotransferase',
    category: ParameterCategoryClass.getName(ParameterCategory.liver),
    upperLimit: 50,
    lowerLimit: 0,
    unit: 'U/L',
  ),
  BloodWorkParameter(
    name: 'Albumin im Serum',
    fullName: 'Albumin in Serum',
    category: ParameterCategoryClass.getName(ParameterCategory.liver),
    upperLimit: 5,
    lowerLimit: 3,
    unit: 'g/dL',
  ),
  BloodWorkParameter(
    name: 'Alkalische Phosphatase',
    fullName: 'Alkaline Phosphatase',
    category: ParameterCategoryClass.getName(ParameterCategory.liver),
    upperLimit: 130,
    lowerLimit: 20,
    unit: 'U/L',
  ),
  BloodWorkParameter(
    name: 'Alpha-Fetoprotein – Tumormarker AFP',
    fullName: 'Alpha-Fetoprotein Tumor Marker AFP',
    category: ParameterCategoryClass.getName(ParameterCategory.cancerMarkers),
    upperLimit: 10,
    lowerLimit: 0,
    unit: 'ng/mL',
  ),
  BloodWorkParameter(
    name: 'Alpha1-Antitrypsin',
    fullName: 'Alpha-1 Antitrypsin',
    category: ParameterCategoryClass.getName(ParameterCategory.liver),
    upperLimit: 40,
    lowerLimit: 20,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'Alpha1-Globuline',
    fullName: 'Alpha-1 Globulins',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 0.3,
    lowerLimit: 0.1,
    unit: 'g/dL',
  ),
  BloodWorkParameter(
    name: 'Alpha2-Globuline',
    fullName: 'Alpha-2 Globulins',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 0.8,
    lowerLimit: 0.3,
    unit: 'g/dL',
  ),
  BloodWorkParameter(
    name: 'AMA',
    fullName: 'Antimitochondrial Antibodies',
    category: ParameterCategoryClass.getName(ParameterCategory.autoimmune),
    upperLimit: 20,
    lowerLimit: 0,
    unit: 'U/mL',
  ),
  BloodWorkParameter(
    name: 'Amylase',
    fullName: 'Amylase',
    category: ParameterCategoryClass.getName(ParameterCategory.pancreas),
    upperLimit: 120,
    lowerLimit: 25,
    unit: 'U/L',
  ),
  BloodWorkParameter(
    name: 'ANA',
    fullName: 'Antinuclear Antibodies',
    category: ParameterCategoryClass.getName(ParameterCategory.autoimmune),
    upperLimit: 1,
    lowerLimit: 0,
    unit: 'U/mL',
  ),
  BloodWorkParameter(
    name: 'Anti-CCP',
    fullName: 'Anti-Cyclic Citrullinated Peptide',
    category: ParameterCategoryClass.getName(ParameterCategory.autoimmune),
    upperLimit: 20,
    lowerLimit: 0,
    unit: 'U/mL',
  ),
  BloodWorkParameter(
    name: 'Anti-ds-DNA',
    fullName: 'Anti-Double Stranded DNA',
    category: ParameterCategoryClass.getName(ParameterCategory.autoimmune),
    upperLimit: 30,
    lowerLimit: 0,
    unit: 'U/mL',
  ),
  BloodWorkParameter(
    name: 'Anti-HBs',
    fullName: 'Hepatitis B Surface Antibodies',
    category: ParameterCategoryClass.getName(ParameterCategory.infection),
    upperLimit: 10,
    lowerLimit: 0,
    unit: 'mIU/mL',
  ),
  BloodWorkParameter(
    name: 'Anti-Müller Hormon',
    fullName: 'Anti-Müllerian Hormone',
    category: ParameterCategoryClass.getName(ParameterCategory.hormones),
    upperLimit: 10,
    lowerLimit: 0,
    unit: 'ng/mL',
  ),
  BloodWorkParameter(
    name: 'Antithrombin 3',
    fullName: 'Antithrombin 3',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 120,
    lowerLimit: 80,
    unit: '%',
  ),
  BloodWorkParameter(
    name: 'ASAT',
    fullName: 'Aspartate Aminotransferase',
    category: ParameterCategoryClass.getName(ParameterCategory.liver),
    upperLimit: 40,
    lowerLimit: 0,
    unit: 'U/L',
  ),
  BloodWorkParameter(
    name: 'ASL-Titer',
    fullName: 'Anti-Streptolysin O Titer',
    category: ParameterCategoryClass.getName(ParameterCategory.infection),
    upperLimit: 200,
    lowerLimit: 0,
    unit: 'U/mL',
  ),
  BloodWorkParameter(
    name: 'ASMA',
    fullName: 'Anti-Smooth Muscle Antibodies',
    category: ParameterCategoryClass.getName(ParameterCategory.autoimmune),
    upperLimit: 20,
    lowerLimit: 0,
    unit: 'U/mL',
  ),

  // B
  BloodWorkParameter(
    name: 'Basophile Granulozyten',
    fullName: 'Basophil Granulocytes',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 2,
    lowerLimit: 0,
    unit: '%',
  ),
  BloodWorkParameter(
    name: 'Beta-Globuline',
    fullName: 'Beta Globulins',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 1,
    lowerLimit: 0,
    unit: 'g/dL',
  ),
  BloodWorkParameter(
    name: 'Beta2-Mikroglobulin',
    fullName: 'Beta-2 Microglobulin',
    category: ParameterCategoryClass.getName(ParameterCategory.kidney),
    upperLimit: 2.5,
    lowerLimit: 0.8,
    unit: 'mg/L',
  ),
  BloodWorkParameter(
    name: 'Bilirubinwert gesamt',
    fullName: 'Total Bilirubin',
    category: ParameterCategoryClass.getName(ParameterCategory.liver),
    upperLimit: 1.2,
    lowerLimit: 0.2,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'Blutdruck',
    fullName: 'Blood Pressure',
    category: ParameterCategoryClass.getName(ParameterCategory.heart),
    upperLimit: 120,
    lowerLimit: 80,
    unit: 'mmHg',
  ),
  BloodWorkParameter(
      name: 'BNP',
      fullName: 'Brain Natriuretic Peptide',
      category: ParameterCategoryClass.getName(ParameterCategory.heart),
      upperLimit: 100,
      lowerLimit: 0,
      unit: 'pg'),
  BloodWorkParameter(
    name: 'BSG Blutsenkung',
    fullName: 'Erythrocyte Sedimentation Rate',
    category: ParameterCategoryClass.getName(ParameterCategory.inflammation),
    upperLimit: 10,
    lowerLimit: 0,
    unit: 'mm/h',
  ),
  BloodWorkParameter(
    name: 'BUN',
    fullName: 'Blood Urea Nitrogen',
    category: ParameterCategoryClass.getName(ParameterCategory.kidney),
    upperLimit: 20,
    lowerLimit: 5,
    unit: 'mg/dL',
  ),

  // C
  BloodWorkParameter(
    name: 'c-ANCA',
    fullName: 'Cytoplasmic Anti-Neutrophil Cytoplasmic Antibodies',
    category: ParameterCategoryClass.getName(ParameterCategory.autoimmune),
    upperLimit: 20,
    lowerLimit: 0,
    unit: 'U/mL',
  ),
  BloodWorkParameter(
    name: 'C-Peptid',
    fullName: 'C-Peptide',
    category: ParameterCategoryClass.getName(ParameterCategory.pancreas),
    upperLimit: 3,
    lowerLimit: 0.5,
    unit: 'ng/mL',
  ),
  BloodWorkParameter(
    name: 'C3 Komplement',
    fullName: 'Complement C3',
    category: ParameterCategoryClass.getName(ParameterCategory.immuneSystem),
    upperLimit: 180,
    lowerLimit: 90,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'C4 Komplement',
    fullName: 'Complement C4',
    category: ParameterCategoryClass.getName(ParameterCategory.immuneSystem),
    upperLimit: 40,
    lowerLimit: 10,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'CA 19-9 Tumormarker',
    fullName: 'CA 19-9 Tumor Marker',
    category: ParameterCategoryClass.getName(ParameterCategory.cancerMarkers),
    upperLimit: 37,
    lowerLimit: 0,
    unit: 'U/mL',
  ),
  BloodWorkParameter(
    name: 'CA-125 Tumormarker',
    fullName: 'CA-125 Tumor Marker',
    category: ParameterCategoryClass.getName(ParameterCategory.cancerMarkers),
    upperLimit: 35,
    lowerLimit: 0,
    unit: 'U/mL',
  ),
  BloodWorkParameter(
    name: 'Calcium',
    fullName: 'Calcium',
    category: ParameterCategoryClass.getName(ParameterCategory.electrolytes),
    upperLimit: 2.6,
    lowerLimit: 2.1,
    unit: 'mmol/L',
  ),
  BloodWorkParameter(
    name: 'CD3 T-Lymphozyten',
    fullName: 'CD3 T-Lymphocytes',
    category: ParameterCategoryClass.getName(ParameterCategory.immuneSystem),
    upperLimit: 2000,
    lowerLimit: 800,
    unit: '/µL',
  ),
  BloodWorkParameter(
    name: 'CD4 – CD8 Quotient',
    fullName: 'CD4 to CD8 Ratio',
    category: ParameterCategoryClass.getName(ParameterCategory.immuneSystem),
    upperLimit: 4,
    lowerLimit: 1,
    unit: 'ratio',
  ),
  BloodWorkParameter(
    name: 'CD4 T-Lymphozyten',
    fullName: 'CD4 T-Lymphocytes',
    category: ParameterCategoryClass.getName(ParameterCategory.immuneSystem),
    upperLimit: 1500,
    lowerLimit: 500,
    unit: '/µL',
  ),
  BloodWorkParameter(
    name: 'CD8 T-Lymphozyten',
    fullName: 'CD8 T-Lymphocytes',
    category: ParameterCategoryClass.getName(ParameterCategory.immuneSystem),
    upperLimit: 1000,
    lowerLimit: 300,
    unit: '/µL',
  ),
  BloodWorkParameter(
    name: 'CEA',
    fullName: 'Carcinoembryonic Antigen',
    category: ParameterCategoryClass.getName(ParameterCategory.cancerMarkers),
    upperLimit: 5,
    lowerLimit: 0,
    unit: 'ng/mL',
  ),
  BloodWorkParameter(
    name: 'Chlorid im Blut',
    fullName: 'Chloride in Blood',
    category: ParameterCategoryClass.getName(ParameterCategory.electrolytes),
    upperLimit: 110,
    lowerLimit: 98,
    unit: 'mmol/L',
  ),
  BloodWorkParameter(
    name: 'Cholesterin',
    fullName: 'Cholesterol',
    category: ParameterCategoryClass.getName(ParameterCategory.heart),
    upperLimit: 200,
    lowerLimit: 0,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'Cholesterin',
    fullName: 'Cholesterol',
    category: ParameterCategoryClass.getName(ParameterCategory.heart),
    upperLimit: 200,
    lowerLimit: 0,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'Ciclosporin A',
    fullName: 'Cyclosporine A',
    category: ParameterCategoryClass.getName(ParameterCategory.immunosuppressants),
    upperLimit: 200,
    lowerLimit: 50,
    unit: 'ng/mL',
  ),
  BloodWorkParameter(
    name: 'CK-MB',
    fullName: 'Creatine Kinase-MB',
    category: ParameterCategoryClass.getName(ParameterCategory.heart),
    upperLimit: 25,
    lowerLimit: 0,
    unit: 'U/L',
  ),
  BloodWorkParameter(
    name: 'Coeruloplasmin',
    fullName: 'Ceruloplasmin',
    category: ParameterCategoryClass.getName(ParameterCategory.liver),
    upperLimit: 50,
    lowerLimit: 20,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'Cortisol',
    fullName: 'Cortisol',
    category: ParameterCategoryClass.getName(ParameterCategory.hormones),
    upperLimit: 20,
    lowerLimit: 5,
    unit: 'µg/dL',
  ),
  BloodWorkParameter(
    name: 'Crosslaps',
    fullName: 'Crosslaps',
    category: ParameterCategoryClass.getName(ParameterCategory.bone),
    upperLimit: 0.5,
    lowerLimit: 0,
    unit: 'ng/mL',
  ),
  BloodWorkParameter(
    name: 'CRP-Wert',
    fullName: 'C-Reactive Protein',
    category: ParameterCategoryClass.getName(ParameterCategory.inflammation),
    upperLimit: 3,
    lowerLimit: 0,
    unit: 'mg/L',
  ),
  BloodWorkParameter(
    name: 'Cystatin C',
    fullName: 'Cystatin C',
    category: ParameterCategoryClass.getName(ParameterCategory.kidney),
    upperLimit: 1,
    lowerLimit: 0.5,
    unit: 'mg/L',
  ),

  // D
  BloodWorkParameter(
    name: 'D-Dimere',
    fullName: 'D-Dimers',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 0.5,
    lowerLimit: 0,
    unit: 'µg/mL',
  ),
  BloodWorkParameter(
    name: 'DHEA-S',
    fullName: 'Dehydroepiandrosterone Sulfate',
    category: ParameterCategoryClass.getName(ParameterCategory.hormones),
    upperLimit: 400,
    lowerLimit: 100,
    unit: 'µg/dL',
  ),
  BloodWorkParameter(
    name: 'direktes Bilirubin',
    fullName: 'Direct Bilirubin',
    category: ParameterCategoryClass.getName(ParameterCategory.liver),
    upperLimit: 0.4,
    lowerLimit: 0,
    unit: 'mg/dL',
  ),

  // E
  BloodWorkParameter(
    name: 'EAG – Estimated Average Glucose',
    fullName: 'Estimated Average Glucose',
    category: ParameterCategoryClass.getName(ParameterCategory.diabetes),
    upperLimit: 120,
    lowerLimit: 80,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'Eisenwert im Blut',
    fullName: 'Iron in Blood',
    category: ParameterCategoryClass.getName(ParameterCategory.vitaminesAndTraceElements),
    upperLimit: 150,
    lowerLimit: 30,
    unit: 'µg/dL',
  ),
  BloodWorkParameter(
    name: 'Eosinophile Granulozyten',
    fullName: 'Eosinophil Granulocytes',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 5,
    lowerLimit: 0,
    unit: '%',
  ),
  BloodWorkParameter(
    name: 'Erythrozyten',
    fullName: 'Erythrocytes',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 4.6,
    lowerLimit: 6.2,
    unit: ' /pl',
  ),

  // F
  BloodWorkParameter(
    name: 'Faktor 13 Aktivität',
    fullName: 'Factor 13 Activity',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 150,
    lowerLimit: 70,
    unit: '%',
  ),
  BloodWorkParameter(
    name: 'Faktor 8 Aktivität',
    fullName: 'Factor 8 Activity',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 150,
    lowerLimit: 70,
    unit: '%',
  ),
  BloodWorkParameter(
    name: 'Ferritinwert',
    fullName: 'Ferritin',
    category: ParameterCategoryClass.getName(ParameterCategory.metabolism),
    upperLimit: 400,
    lowerLimit: 30,
    unit: 'ng/mL',
  ),
  BloodWorkParameter(
    name: 'Fibrinogen',
    fullName: 'Fibrinogen',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 400,
    lowerLimit: 200,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'Flüssigkeits-Aufnahme',
    fullName: 'Fluid Intake',
    category: ParameterCategoryClass.getName(ParameterCategory.general),
    upperLimit: 4000,
    lowerLimit: 1500,
    unit: 'mL',
  ),
  BloodWorkParameter(
    name: 'Folsäure',
    fullName: 'Folic Acid',
    category: ParameterCategoryClass.getName(ParameterCategory.vitaminesAndTraceElements),
    upperLimit: 20,
    lowerLimit: 5,
    unit: 'ng/mL',
  ),
  BloodWorkParameter(
    name: 'FSH-Hormon',
    fullName: 'Follicle-Stimulating Hormone',
    category: ParameterCategoryClass.getName(ParameterCategory.hormones),
    upperLimit: 15,
    lowerLimit: 1,
    unit: 'mIU/mL',
  ),
  BloodWorkParameter(
    name: 'fT3-Wert',
    fullName: 'Free Triiodothyronine',
    category: ParameterCategoryClass.getName(ParameterCategory.thyroid),
    upperLimit: 4.2,
    lowerLimit: 2.5,
    unit: 'pg/mL',
  ),
  BloodWorkParameter(
    name: 'fT4-Wert',
    fullName: 'Free Thyroxine',
    category: ParameterCategoryClass.getName(ParameterCategory.thyroid),
    upperLimit: 1.7,
    lowerLimit: 0.7,
    unit: 'ng/dL',
  ),

  // G
  BloodWorkParameter(
    name: 'Gamma-Globuline',
    fullName: 'Gamma Globulins',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 1.5,
    lowerLimit: 0.5,
    unit: 'g/dL',
  ),
  BloodWorkParameter(
    name: 'Gastrin',
    fullName: 'Gastrin',
    category: ParameterCategoryClass.getName(ParameterCategory.stomach),
    upperLimit: 150,
    lowerLimit: 0,
    unit: 'pg/mL',
  ),
  BloodWorkParameter(
    name: 'GFR Blutwert',
    fullName: 'Glomerular Filtration Rate',
    category: ParameterCategoryClass.getName(ParameterCategory.kidney),
    upperLimit: 120,
    lowerLimit: 90,
    unit: 'ml/min',
  ),
  BloodWorkParameter(
    name: 'GLDH',
    fullName: 'Glutamate Dehydrogenase',
    category: ParameterCategoryClass.getName(ParameterCategory.liver),
    upperLimit: 40,
    lowerLimit: 5,
    unit: 'U/L',
  ),
  BloodWorkParameter(
    name: 'Glukose – Blutzuckerspiegel',
    fullName: 'Glucose - Blood Sugar Level',
    category: ParameterCategoryClass.getName(ParameterCategory.diabetes),
    upperLimit: 100,
    lowerLimit: 70,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'GOT',
    fullName: 'Glutamic Oxaloacetic Transaminase',
    category: ParameterCategoryClass.getName(ParameterCategory.liver),
    upperLimit: 35,
    lowerLimit: 0,
    unit: 'U/L',
  ),
  BloodWorkParameter(
    name: 'GPT',
    fullName: 'Glutamic Pyruvic Transaminase',
    category: ParameterCategoryClass.getName(ParameterCategory.liver),
    upperLimit: 40,
    lowerLimit: 0,
    unit: 'U/L',
  ),

  // H
  BloodWorkParameter(
    name: 'Hämatokrit',
    fullName: 'Hematocrit',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 54,
    lowerLimit: 38,
    unit: '%',
  ),
  BloodWorkParameter(
    name: 'Hämoglobin',
    fullName: 'Hemoglobin',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 17,
    lowerLimit: 12,
    unit: 'g/dL',
  ),
  BloodWorkParameter(
    name: 'Harnsäure',
    fullName: 'Uric Acid',
    category: ParameterCategoryClass.getName(ParameterCategory.metabolism),
    upperLimit: 7,
    lowerLimit: 2,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'Harnstoff',
    fullName: 'Urea',
    category: ParameterCategoryClass.getName(ParameterCategory.kidney),
    upperLimit: 20,
    lowerLimit: 7,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'HbA1c Wert',
    fullName: 'Hemoglobin A1c',
    category: ParameterCategoryClass.getName(ParameterCategory.diabetes),
    upperLimit: 6,
    lowerLimit: 4,
    unit: '%',
  ),
  BloodWorkParameter(
    name: 'HBV-Infektion',
    fullName: 'Hepatitis B Virus Infection',
    category: ParameterCategoryClass.getName(ParameterCategory.infection),
    upperLimit: 0,
    lowerLimit: 0,
    unit: 'positive/negative',
  ),
  BloodWorkParameter(
    name: 'HCG-Hormon',
    fullName: 'Human Chorionic Gonadotropin Hormone',
    category: ParameterCategoryClass.getName(ParameterCategory.hormones),
    upperLimit: 5,
    lowerLimit: 0,
    unit: 'mIU/mL',
  ),
  BloodWorkParameter(
    name: 'HCV Viruslast',
    fullName: 'Hepatitis C Virus Load',
    category: ParameterCategoryClass.getName(ParameterCategory.infection),
    upperLimit: 1000000,
    lowerLimit: 0,
    unit: 'IU/mL',
  ),
  BloodWorkParameter(
    name: 'HDL Cholesterin',
    fullName: 'High-Density Lipoprotein Cholesterol',
    category: ParameterCategoryClass.getName(ParameterCategory.heart),
    upperLimit: 60,
    lowerLimit: 40,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'HIV-Viruslast',
    fullName: 'Human Immunodeficiency Virus Load',
    category: ParameterCategoryClass.getName(ParameterCategory.infection),
    upperLimit: 500000,
    lowerLimit: 0,
    unit: 'copies/mL',
  ),
  BloodWorkParameter(
    name: 'Homocysteinwert',
    fullName: 'Homocysteine',
    category: ParameterCategoryClass.getName(ParameterCategory.heart),
    upperLimit: 15,
    lowerLimit: 5,
    unit: 'µmol/L',
  ),

  // I
  BloodWorkParameter(
    name: 'IgA',
    fullName: 'Immunoglobulin A',
    category: ParameterCategoryClass.getName(ParameterCategory.immuneSystem),
    upperLimit: 400,
    lowerLimit: 70,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'IgE',
    fullName: 'Immunoglobulin E',
    category: ParameterCategoryClass.getName(ParameterCategory.immuneSystem),
    upperLimit: 150,
    lowerLimit: 5,
    unit: 'IU/mL',
  ),
  BloodWorkParameter(
    name: 'IgG',
    fullName: 'Immunoglobulin G',
    category: ParameterCategoryClass.getName(ParameterCategory.immuneSystem),
    upperLimit: 1500,
    lowerLimit: 700,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'IgM',
    fullName: 'Immunoglobulin M',
    category: ParameterCategoryClass.getName(ParameterCategory.immuneSystem),
    upperLimit: 300,
    lowerLimit: 40,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'indirektes Bilirubin',
    fullName: 'Indirect Bilirubin',
    category: ParameterCategoryClass.getName(ParameterCategory.liver),
    upperLimit: 0.9,
    lowerLimit: 0,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'INR',
    fullName: 'International Normalized Ratio',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 1.1,
    lowerLimit: 0.9,
    unit: 'ratio',
  ),
  BloodWorkParameter(
    name: 'Insulin',
    fullName: 'Insulin',
    category: ParameterCategoryClass.getName(ParameterCategory.pancreas),
    upperLimit: 20,
    lowerLimit: 0,
    unit: 'µU/mL',
  ),

  // K
  BloodWorkParameter(
    name: 'Kalium',
    fullName: 'Potassium',
    category: ParameterCategoryClass.getName(ParameterCategory.electrolytes),
    upperLimit: 5,
    lowerLimit: 3.5,
    unit: 'mmol/L',
  ),
  BloodWorkParameter(
    name: 'Körpergewicht',
    fullName: 'Body Weight',
    category: ParameterCategoryClass.getName(ParameterCategory.general),
    upperLimit: 200,
    lowerLimit: 50,
    unit: 'kg',
  ),
  BloodWorkParameter(
    name: 'Körpergröße',
    fullName: 'Body Height',
    category: ParameterCategoryClass.getName(ParameterCategory.general),
    upperLimit: 200,
    lowerLimit: 50,
    unit: 'cm',
  ),
  // L
  BloodWorkParameter(
    name: 'LDH',
    fullName: 'Lactate Dehydrogenase',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 250,
    lowerLimit: 100,
    unit: 'U/L',
  ),
  BloodWorkParameter(
    name: 'LDL Cholesterin',
    fullName: 'Low-Density Lipoprotein Cholesterol',
    category: ParameterCategoryClass.getName(ParameterCategory.heart),
    upperLimit: 130,
    lowerLimit: 0,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'Leberwerte',
    fullName: 'Liver Values',
    category: ParameterCategoryClass.getName(ParameterCategory.liver),
    upperLimit: 40,
    lowerLimit: 0,
    unit: 'U/L',
  ),
  BloodWorkParameter(
    name: 'Leukozyten',
    fullName: 'Leukocytes',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 11,
    lowerLimit: 4,
    unit: '/µL',
  ),
  BloodWorkParameter(
    name: 'LH-Hormon',
    fullName: 'Luteinizing Hormone',
    category: ParameterCategoryClass.getName(ParameterCategory.hormones),
    upperLimit: 12,
    lowerLimit: 1,
    unit: 'mIU/mL',
  ),
  BloodWorkParameter(
    name: 'Lipase',
    fullName: 'Lipase',
    category: ParameterCategoryClass.getName(ParameterCategory.pancreas),
    upperLimit: 60,
    lowerLimit: 13,
    unit: 'U/L',
  ),
  BloodWorkParameter(
    name: 'Lipoprotein(a)',
    fullName: 'Lipoprotein(a)',
    category: ParameterCategoryClass.getName(ParameterCategory.heart),
    upperLimit: 30,
    lowerLimit: 0,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'Lues – Syphilis',
    fullName: 'Syphilis',
    category: ParameterCategoryClass.getName(ParameterCategory.infection),
    upperLimit: 0,
    lowerLimit: 0,
    unit: 'positive/negative',
  ),
  BloodWorkParameter(
    name: 'Lungenfunktion',
    fullName: 'Lung Function',
    category: ParameterCategoryClass.getName(ParameterCategory.respiratory),
    upperLimit: 120,
    lowerLimit: 80,
    unit: '%',
  ),

  // M
  BloodWorkParameter(
    name: 'Magnesium',
    fullName: 'Magnesium',
    category: ParameterCategoryClass.getName(ParameterCategory.electrolytes),
    upperLimit: 2.5,
    lowerLimit: 1.7,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'MCV',
    fullName: 'Mean Corpuscular Volume',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 100,
    lowerLimit: 80,
    unit: 'fL',
  ),
  BloodWorkParameter(
    name: 'MCH',
    fullName: 'Mean Corpuscular Hemoglobin',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 33,
    lowerLimit: 27,
    unit: 'pg',
  ),
  BloodWorkParameter(
    name: 'MCHC',
    fullName: 'Mean Corpuscular Hemoglobin Concentration',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 36,
    lowerLimit: 31,
    unit: 'g/dL',
  ),
  BloodWorkParameter(
    name: 'Mikroalbuminurie',
    fullName: 'Microalbuminuria',
    category: ParameterCategoryClass.getName(ParameterCategory.kidney),
    upperLimit: 30,
    lowerLimit: 0,
    unit: 'mg/g',
  ),
  BloodWorkParameter(
    name: 'Monozyten',
    fullName: 'Monocytes',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 12,
    lowerLimit: 4,
    unit: '%',
  ),

  // N
  BloodWorkParameter(
    name: 'Natrium',
    fullName: 'Sodium',
    category: ParameterCategoryClass.getName(ParameterCategory.electrolytes),
    upperLimit: 145,
    lowerLimit: 135,
    unit: 'mmol/L',
  ),
  BloodWorkParameter(
    name: 'Neutrophile Granulozyten',
    fullName: 'Neutrophil Granulocytes',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 70,
    lowerLimit: 40,
    unit: '%',
  ),
  BloodWorkParameter(
    name: 'Nierenwerte',
    fullName: 'Kidney Values',
    category: ParameterCategoryClass.getName(ParameterCategory.kidney),
    upperLimit: 1.2,
    lowerLimit: 0.7,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'Nitrit im Urin',
    fullName: 'Nitrite in Urine',
    category: ParameterCategoryClass.getName(ParameterCategory.urinary),
    upperLimit: 0,
    lowerLimit: 0,
    unit: 'positive/negative',
  ),

  // O
  BloodWorkParameter(
    name: 'Östradiol',
    fullName: 'Estradiol',
    category: ParameterCategoryClass.getName(ParameterCategory.hormones),
    upperLimit: 50,
    lowerLimit: 0,
    unit: 'pg/mL',
  ),
  BloodWorkParameter(
    name: 'Östron',
    fullName: 'Estrone',
    category: ParameterCategoryClass.getName(ParameterCategory.hormones),
    upperLimit: 80,
    lowerLimit: 10,
    unit: 'pg/mL',
  ),

  // P
  BloodWorkParameter(
    name: 'pH-Wert im Urin',
    fullName: 'pH Value in Urine',
    category: ParameterCategoryClass.getName(ParameterCategory.urinary),
    upperLimit: 8,
    lowerLimit: 5,
    unit: '',
  ),
  BloodWorkParameter(
    name: 'Phosphat',
    fullName: 'Phosphate',
    category: ParameterCategoryClass.getName(ParameterCategory.vitaminesAndTraceElements),
    upperLimit: 4.5,
    lowerLimit: 2.5,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'Phospholipide',
    fullName: 'Phospholipids',
    category: ParameterCategoryClass.getName(ParameterCategory.liver),
    upperLimit: 250,
    lowerLimit: 100,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'Plasminogen-Aktivator-Inhibitor',
    fullName: 'Plasminogen Activator Inhibitor',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 5,
    lowerLimit: 0,
    unit: 'U/mL',
  ),
  BloodWorkParameter(
    name: 'Proinsulin',
    fullName: 'Proinsulin',
    category: ParameterCategoryClass.getName(ParameterCategory.pancreas),
    upperLimit: 25,
    lowerLimit: 3,
    unit: 'pmol/L',
  ),
  BloodWorkParameter(
    name: 'Protein im Urin',
    fullName: 'Protein in Urine',
    category: ParameterCategoryClass.getName(ParameterCategory.urinary),
    upperLimit: 150,
    lowerLimit: 0,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'PSA-Wert',
    fullName: 'Prostate-Specific Antigen',
    category: ParameterCategoryClass.getName(ParameterCategory.cancerMarkers),
    upperLimit: 4,
    lowerLimit: 0,
    unit: 'ng/mL',
  ),

  // R
  BloodWorkParameter(
    name: 'Retikulozyten',
    fullName: 'Reticulocytes',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 1,
    lowerLimit: 0.5,
    unit: '%',
  ),

  // S
  BloodWorkParameter(
    name: 'Schilddrüsenantikörper',
    fullName: 'Thyroid Antibodies',
    category: ParameterCategoryClass.getName(ParameterCategory.thyroid),
    upperLimit: 4,
    lowerLimit: 0,
    unit: 'U/mL',
  ),
  BloodWorkParameter(
    name: 'Selen im Blut',
    fullName: 'Selenium in Blood',
    category: ParameterCategoryClass.getName(ParameterCategory.vitaminesAndTraceElements),
    upperLimit: 150,
    lowerLimit: 70,
    unit: 'µg/L',
  ),
  BloodWorkParameter(
    name: 'Serotonin',
    fullName: 'Serotonin',
    category: ParameterCategoryClass.getName(ParameterCategory.neurotransmitters),
    upperLimit: 400,
    lowerLimit: 150,
    unit: 'ng/mL',
  ),
  BloodWorkParameter(
    name: 'SGLT-2-Inhibitoren',
    fullName: 'SGLT-2 Inhibitors',
    category: ParameterCategoryClass.getName(ParameterCategory.diabetes),
    upperLimit: 0,
    lowerLimit: 0,
    unit: 'positive/negative',
  ),
  BloodWorkParameter(
    name: 'SHBG',
    fullName: 'Sex Hormone-Binding Globulin',
    category: ParameterCategoryClass.getName(ParameterCategory.hormones),
    upperLimit: 120,
    lowerLimit: 20,
    unit: 'nmol/L',
  ),
  BloodWorkParameter(
    name: 'Sirolimus',
    fullName: 'Sirolimus',
    category: ParameterCategoryClass.getName(ParameterCategory.immunosuppressants),
    upperLimit: 10,
    lowerLimit: 2,
    unit: 'ng/mL',
  ),
  BloodWorkParameter(
    name: 'Sjögren Syndrom A (SS-A)',
    fullName: 'Sjögren Syndrome A (SS-A)',
    category: ParameterCategoryClass.getName(ParameterCategory.autoimmune),
    upperLimit: 20,
    lowerLimit: 0,
    unit: 'U/mL',
  ),
  BloodWorkParameter(
    name: 'Sjögren Syndrom B (SS-B)',
    fullName: 'Sjögren Syndrome B (SS-B)',
    category: ParameterCategoryClass.getName(ParameterCategory.autoimmune),
    upperLimit: 20,
    lowerLimit: 0,
    unit: 'U/mL',
  ),
  BloodWorkParameter(
    name: 'Sorbitol-Dehydrogenase',
    fullName: 'Sorbitol Dehydrogenase',
    category: ParameterCategoryClass.getName(ParameterCategory.liver),
    upperLimit: 20,
    lowerLimit: 5,
    unit: 'U/L',
  ),
  BloodWorkParameter(
    name: 'Spezifisches Gewicht im Urin',
    fullName: 'Specific Gravity in Urine',
    category: ParameterCategoryClass.getName(ParameterCategory.urinary),
    upperLimit: 1.03,
    lowerLimit: 1.01,
    unit: '',
  ),
  BloodWorkParameter(
    name: 'Stuhlfett',
    fullName: 'Fecal Fat',
    category: ParameterCategoryClass.getName(ParameterCategory.digestiveSystem),
    upperLimit: 7,
    lowerLimit: 0,
    unit: 'g/d',
  ),
  BloodWorkParameter(
    name: 'Summe Eosinophile Granulozyten',
    fullName: 'Total Eosinophil Granulocytes',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 6,
    lowerLimit: 0,
    unit: '%',
  ),
  BloodWorkParameter(
    name: 'Summe Monozyten',
    fullName: 'Total Monocytes',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 12,
    lowerLimit: 0,
    unit: '%',
  ),
  BloodWorkParameter(
    name: 'Summe Neutrophile Granulozyten',
    fullName: 'Total Neutrophil Granulocytes',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 70,
    lowerLimit: 40,
    unit: '%',
  ),
  BloodWorkParameter(
    name: 'Summe Lymphozyten',
    fullName: 'Total Lymphocytes',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 40,
    lowerLimit: 20,
    unit: '%',
  ),
  BloodWorkParameter(
    name: 'Synacthen Test',
    fullName: 'Synacthen Test',
    category: ParameterCategoryClass.getName(ParameterCategory.hormones),
    upperLimit: 200,
    lowerLimit: 0,
    unit: 'pg/mL',
  ),

  // T
  BloodWorkParameter(
    name: 'T3-Wert',
    fullName: 'Triiodothyronine',
    category: ParameterCategoryClass.getName(ParameterCategory.thyroid),
    upperLimit: 181,
    lowerLimit: 71,
    unit: 'ng/dL',
  ),
  BloodWorkParameter(
    name: 'T3 freies Hormon',
    fullName: 'Free Triiodothyronine',
    category: ParameterCategoryClass.getName(ParameterCategory.thyroid),
    upperLimit: 4.2,
    lowerLimit: 2.5,
    unit: 'pg/mL',
  ),
  BloodWorkParameter(
    name: 'T4 freies Hormon',
    fullName: 'Free Thyroxine',
    category: ParameterCategoryClass.getName(ParameterCategory.thyroid),
    upperLimit: 1.7,
    lowerLimit: 0.7,
    unit: 'ng/dL',
  ),
  BloodWorkParameter(
    name: 'Testosteron',
    fullName: 'Testosterone',
    category: ParameterCategoryClass.getName(ParameterCategory.hormones),
    upperLimit: 10,
    lowerLimit: 2,
    unit: 'ng/mL',
  ),
  BloodWorkParameter(
    name: 'Thrombinzeit',
    fullName: 'Thrombin Time',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 20,
    lowerLimit: 13,
    unit: 's',
  ),
  BloodWorkParameter(
    name: 'Thrombozyten',
    fullName: 'Platelets (Thrombocytes)',
    category: ParameterCategoryClass.getName(ParameterCategory.blood),
    upperLimit: 400,
    lowerLimit: 150,
    unit: '/µL',
  ),
  BloodWorkParameter(
    name: 'Thyreoglobulin',
    fullName: 'Thyroglobulin',
    category: ParameterCategoryClass.getName(ParameterCategory.thyroid),
    upperLimit: 60,
    lowerLimit: 0,
    unit: 'ng/mL',
  ),
  BloodWorkParameter(
    name: 'Thyreoperoxidase-Antikörper (TPO-AK)',
    fullName: 'Thyroid Peroxidase Antibodies',
    category: ParameterCategoryClass.getName(ParameterCategory.thyroid),
    upperLimit: 35,
    lowerLimit: 0,
    unit: 'U/mL',
  ),
  BloodWorkParameter(
    name: 'Thyreotropin Rezeptor Antikörper (TRAK)',
    fullName: 'Thyrotropin Receptor Antibodies',
    category: ParameterCategoryClass.getName(ParameterCategory.thyroid),
    upperLimit: 1.5,
    lowerLimit: 0,
    unit: 'U/L',
  ),
  BloodWorkParameter(
    name: 'Transferrin',
    fullName: 'Transferrin',
    category: ParameterCategoryClass.getName(ParameterCategory.metabolism),
    upperLimit: 360,
    lowerLimit: 200,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'TSH-Hormon',
    fullName: 'Thyroid Stimulating Hormone',
    category: ParameterCategoryClass.getName(ParameterCategory.thyroid),
    upperLimit: 4,
    lowerLimit: 0.3,
    unit: 'µIU/mL',
  ),

  // U
  BloodWorkParameter(
    name: 'Urate',
    fullName: 'Urate',
    category: ParameterCategoryClass.getName(ParameterCategory.metabolism),
    upperLimit: 7,
    lowerLimit: 2,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'Urea im Urin',
    fullName: 'Urea in Urine',
    category: ParameterCategoryClass.getName(ParameterCategory.urinary),
    upperLimit: 20,
    lowerLimit: 10,
    unit: 'g/dL',
  ),
  BloodWorkParameter(
    name: 'Urobilinogen im Urin',
    fullName: 'Urobilinogen in Urine',
    category: ParameterCategoryClass.getName(ParameterCategory.urinary),
    upperLimit: 1,
    lowerLimit: 0,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'Urin Kreatinin',
    fullName: 'Urine Creatinine',
    category: ParameterCategoryClass.getName(ParameterCategory.urinary),
    upperLimit: 2500,
    lowerLimit: 500,
    unit: 'mg/dL',
  ),
  BloodWorkParameter(
    name: 'Urin pH-Wert',
    fullName: 'Urine pH Value',
    category: ParameterCategoryClass.getName(ParameterCategory.urinary),
    upperLimit: 8,
    lowerLimit: 5,
    unit: '',
  ),
  BloodWorkParameter(
    name: 'Urin-Protein-Kreatinin-Quotient',
    fullName: 'Urine Protein-to-Creatinine Ratio',
    category: ParameterCategoryClass.getName(ParameterCategory.urinary),
    upperLimit: 200,
    lowerLimit: 0,
    unit: 'mg/g',
  ),

  // V
  BloodWorkParameter(
    name: 'Vitamin A',
    fullName: 'Vitamin A',
    category: ParameterCategoryClass.getName(ParameterCategory.vitaminesAndTraceElements),
    upperLimit: 80,
    lowerLimit: 20,
    unit: 'µg/dL',
  ),
  BloodWorkParameter(
    name: 'Vitamin B1',
    fullName: 'Vitamin B1',
    category: ParameterCategoryClass.getName(ParameterCategory.vitaminesAndTraceElements),
    upperLimit: 1.5,
    lowerLimit: 0.2,
    unit: 'µg/L',
  ),
  BloodWorkParameter(
    name: 'Vitamin B12',
    fullName: 'Vitamin B12',
    category: ParameterCategoryClass.getName(ParameterCategory.vitaminesAndTraceElements),
    upperLimit: 900,
    lowerLimit: 200,
    unit: 'pg/mL',
  ),
  BloodWorkParameter(
    name: 'Vitamin B2',
    fullName: 'Vitamin B2',
    category: ParameterCategoryClass.getName(ParameterCategory.vitaminesAndTraceElements),
    upperLimit: 7,
    lowerLimit: 2,
    unit: 'µg/L',
  ),
  BloodWorkParameter(
    name: 'Vitamin B6',
    fullName: 'Vitamin B6',
    category: ParameterCategoryClass.getName(ParameterCategory.vitaminesAndTraceElements),
    upperLimit: 50,
    lowerLimit: 5,
    unit: 'µg/L',
  ),
  BloodWorkParameter(
    name: 'Vitamin C',
    fullName: 'Vitamin C',
    category: ParameterCategoryClass.getName(ParameterCategory.vitaminesAndTraceElements),
    upperLimit: 2,
    lowerLimit: 0.2,
    unit: 'mg/L',
  ),
  BloodWorkParameter(
    name: 'Vitamin D (25-OH)',
    fullName: 'Vitamin D (25-Hydroxy)',
    category: ParameterCategoryClass.getName(ParameterCategory.vitaminesAndTraceElements),
    upperLimit: 50,
    lowerLimit: 30,
    unit: 'ng/mL',
  ),
  BloodWorkParameter(
    name: 'Vitamin E',
    fullName: 'Vitamin E',
    category: ParameterCategoryClass.getName(ParameterCategory.vitaminesAndTraceElements),
    upperLimit: 18,
    lowerLimit: 5,
    unit: 'µg/L',
  ),
  BloodWorkParameter(
    name: 'Vitamin K',
    fullName: 'Vitamin K',
    category: ParameterCategoryClass.getName(ParameterCategory.vitaminesAndTraceElements),
    upperLimit: 2.5,
    lowerLimit: 0.2,
    unit: 'ng/mL',
  ),

  // W
  BloodWorkParameter(
    name: 'Weizen-Antikörper',
    fullName: 'Wheat Antibodies',
    category: ParameterCategoryClass.getName(ParameterCategory.allergies),
    upperLimit: 0,
    lowerLimit: 0,
    unit: 'positive/negative',
  ),

  // Z
  BloodWorkParameter(
    name: 'Zink',
    fullName: 'Zinc',
    category: ParameterCategoryClass.getName(ParameterCategory.vitaminesAndTraceElements),
    upperLimit: 150,
    lowerLimit: 60,
    unit: 'µg/dL',
  ),
];

List<MedicationComponent> componentsInitial = [
  MedicationComponent(
    name: 'Testosterone',
    fullName: 'Testo',
    category: ComponentCategoryClass.getName(ComponentCategory.hormoneReplacementTherapy),
    unit: 'mg',
    typeToHalfLife: {'Enanthate': 4.5, 'Cypionate': 4.5, 'Propionate': 1.5},
  ),
  // Medication Component deca
  MedicationComponent(
    name: 'Deca',
    fullName: 'Deca',
    category: ComponentCategoryClass.getName(ComponentCategory.hormoneReplacementTherapy),
    unit: 'mg',
    typeToHalfLife: {'Decanoate': 15},
  ),

  // Medication Component tren
  MedicationComponent(
    name: 'Trenbolone',
    fullName: 'Tren',
    category: ComponentCategoryClass.getName(ComponentCategory.hormoneReplacementTherapy),
    unit: 'mg',
    typeToHalfLife: {'Enanthate': 5, 'Acetate': 2},
  ),

  // Medication Component boldenone
  MedicationComponent(
    name: 'Boldenone',
    fullName: 'Bold',
    category: ComponentCategoryClass.getName(ComponentCategory.hormoneReplacementTherapy),
    unit: 'mg',
    typeToHalfLife: {'Undecylenate': 14},
  ),

  // Medication Component masteron
  MedicationComponent(
    name: 'Masteron',
    fullName: 'Masteron',
    category: ComponentCategoryClass.getName(ComponentCategory.hormoneReplacementTherapy),
    unit: 'mg',
    typeToHalfLife: {'Propionate': 1.5},
  ),

  // Medication Component primobolan
  MedicationComponent(
    name: 'Primobolan',
    fullName: 'Primo',
    category: ComponentCategoryClass.getName(ComponentCategory.hormoneReplacementTherapy),
    unit: 'mg',
    typeToHalfLife: {'Enanthate': 10},
  ),

  // Medication Component anavar
  MedicationComponent(
    name: 'Anavar',
    fullName: 'Anavar',
    category: ComponentCategoryClass.getName(ComponentCategory.hormoneReplacementTherapy),
    unit: 'mg',
    typeToHalfLife: {'Oxandrolone': 9},
  ),

  // Medication Component winstrol
  MedicationComponent(
    name: 'Winstrol',
    fullName: 'Winstrol',
    category: ComponentCategoryClass.getName(ComponentCategory.hormoneReplacementTherapy),
    unit: 'mg',
    typeToHalfLife: {'Stanozolol': 9},
  ),

  // Medication Component dianabol
  MedicationComponent(
    name: 'Dianabol',
    fullName: 'Dianabol',
    category: ComponentCategoryClass.getName(ComponentCategory.hormoneReplacementTherapy),
    unit: 'mg',
    typeToHalfLife: {'Methandienone': 4.5},
  ),

  // Medication Component anadrol
  MedicationComponent(
    name: 'Anadrol',
    fullName: 'Anadrol',
    category: ComponentCategoryClass.getName(ComponentCategory.hormoneReplacementTherapy),
    unit: 'mg',
    typeToHalfLife: {'Oxymetholone': 9},
  ),

  // Medication Component proviron
  MedicationComponent(
    name: 'Proviron',
    fullName: 'Proviron',
    category: ComponentCategoryClass.getName(ComponentCategory.hormoneReplacementTherapy),
    unit: 'mg',
    typeToHalfLife: {'Mesterolone': 12},
  ),

  // Medication Component arimidex

  MedicationComponent(
    name: 'Arimidex',
    fullName: 'Arimidex',
    category: ComponentCategoryClass.getName(ComponentCategory.aromataseInhibitor),
    unit: 'mg',
    typeToHalfLife: {'Anastrozole': 2},
  ),

  // Medication Component aromasin

  MedicationComponent(
    name: 'Aromasin',
    fullName: 'Aromasin',
    category: ComponentCategoryClass.getName(ComponentCategory.aromataseInhibitor),
    unit: 'mg',
    typeToHalfLife: {'Exemestane': 1.5},
  ),

  // Medication Component nolvadex

  MedicationComponent(
    name: 'Nolvadex',
    fullName: 'Nolvadex',
    category: ComponentCategoryClass.getName(ComponentCategory.pct),
    unit: 'mg',
    typeToHalfLife: {'Tamoxifen': 5},
  ),

  // Medication Component clomid

  MedicationComponent(
    name: 'Clomid',
    fullName: 'Clomid',
    category: ComponentCategoryClass.getName(ComponentCategory.pct),
    unit: 'mg',
    typeToHalfLife: {'Clomiphene': 5},
  ),

  // Medication Component hcg

  MedicationComponent(
    name: 'HCG',
    fullName: 'HCG',
    category: ComponentCategoryClass.getName(ComponentCategory.pct),
    unit: 'IU',
    typeToHalfLife: {'HCG': 1},
  ),

  // Medication Component hgh

  MedicationComponent(
    name: 'HGH',
    fullName: 'HGH',
    category: ComponentCategoryClass.getName(ComponentCategory.hormoneReplacementTherapy),
    unit: 'IU',
    typeToHalfLife: {'HGH': 1},
  ),
];
