enum ParameterCategory {
  heart,
  blood,
  kidney,
  liver,
  electrolytes,
  vitaminesAndTraceElements,
  cancerMarkers,
  autoimmune,
  pancreas,
  infection,
  hormones,
  inflammation,
  immuneSystem,
  immunosuppressants,
  bone,
  diabetes,
  general,
  thyroid,
  stomach,
  metabolism,
  respiratory,
  urinary,
  neurotransmitters,
  digestiveSystem,
  allergies
}

class ParameterCategoryClass {
  static const Map<ParameterCategory, String> names = {
    ParameterCategory.heart: 'Cardiovascular System',
    ParameterCategory.blood: 'Blood',
    ParameterCategory.kidney: 'Kidney',
    ParameterCategory.liver: 'Liver',
    ParameterCategory.electrolytes: 'Electrolytes',
    ParameterCategory.cancerMarkers: 'Cancer Markers',
    ParameterCategory.autoimmune: 'Autoimmune',
    ParameterCategory.vitaminesAndTraceElements: 'Vitamins + Trace Elements',
    ParameterCategory.pancreas: 'Pancreas',
    ParameterCategory.infection: 'Infection',
    ParameterCategory.hormones: 'Hormones',
    ParameterCategory.inflammation: 'Inflammation',
    ParameterCategory.immuneSystem: 'Immune System',
    ParameterCategory.immunosuppressants: 'Immunosuppressants',
    ParameterCategory.bone: 'Bone',
    ParameterCategory.diabetes: 'Diabetes',
    ParameterCategory.general: 'General',
    ParameterCategory.thyroid: 'Thyroid',
    ParameterCategory.stomach: 'Stomach',
    ParameterCategory.metabolism: 'Metabolism',
    ParameterCategory.respiratory: 'Respiratory',
    ParameterCategory.urinary: 'Urinary',
    ParameterCategory.neurotransmitters: 'Neurotransmitters',
    ParameterCategory.digestiveSystem: 'Digestive System',
    ParameterCategory.allergies: 'Allergies',
  };

  static String getName(ParameterCategory type) => names[type]!;
}

final List<String> categories = [
  'Cardiovascular System',
  'Blood',
  'Kidney',
  'Liver',
  'Electrolytes',
  'Vitamins + Trace Elements',
  'Cancer Markers',
  'Autoimmune',
  'Pancreas',
  'Infection',
  'Hormones',
  'Inflammation',
  'Immune System',
  'Immunosuppressants',
  'Bone',
  'Diabetes',
  'General',
  'Thyroid',
  'Stomach',
  'Metabolism',
  'Respiratory',
  'Urinary',
  'Neurotransmitters',
  'Digestive System',
  'Allergies',
];
